[Variables]
FontFace=Roboto Mono Italic
FontSize=14
Padding=10
TitleWidth=200
TitleHeight=25

; Include whichever color scheme you want here.
@include=Colors White.inc
; @include=Colors Black.inc

[sBg]
W=#TitleWidth#
H=#TitleHeight#
SolidColor=0,0,0,1

[sTitle]
FontFace=#FontFace#
FontSize=#FontSize#
FontColor=#FontColor#
StringAlign=Right
AntiAlias=1
W=#TitleWidth#
H=#TitleHeight#
X=#TitleWidth#
